.LP
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Donec hendrerit tempor tellus.
Donec pretium posuere tellus.
.bp
.PP
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus.
Nulla posuere.
Donec vitae dolor.
.bp
.PP
Pellentesque dapibus suscipit ligula.
Donec posuere augue in quam.
Suspendisse potenti.
.PP
The following does not mark a pagebreak unless the interpretation of
LaTeX commands in plain paragraphs is enabled.
.PP
\[rs]pagebreak
.PP
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus.
.PP
Final paragraph without a preceding pagebreak.
